### ISSUE TITLE
Add EVC LED control

### ISSUE THREAD

**Issue by PhillyGilly** [britkat1980/ha-addons#22]
An enhancement request, please.
The ability to turn the LEDs on and off would be very useful. As my EVC is near the roadside, I like to turn off the LEDs when it's not being used to make it a bit less conspicuous.

A possible solution would be the creation of a new entity e.g. input_select.givtcp_87023906845470_led_status.

By way of background this is how I do it outside GivTCP:
This functionality and code below was lifted from @olivershingler website (https://www.speaktothegeek.co.uk/2023/10/givenergy-ev-charger-and-home-assistant-using-the-cloud-api/)

![image](https://github.com/user-attachments/assets/b9fb6593-033c-4e1b-a0ac-20905e0687df)

in configuration.yaml
```
switch: !include switch.yaml
rest_command: !include rest_command.yaml
rest: !include rest.yaml
```
in switch.yaml
```
- platform: template
  switches:
      givenergy_ev_leds:
        friendly_name: "GivEnergy EV LEDs"
        value_template: "{{ is_state('binary_sensor.givenergy_ev_led_state', 'on') }}"
        turn_on:
          service: rest_command.givenergy_ev_leds
          data:
            value: "1"
        turn_off:
          service: rest_command.givenergy_ev_leds
          data:
            value: "0"
```
in rest.yaml
```
- resource_template: 'https://api.givenergy.cloud/v1/ev-charger?page=1'
  scan_interval: 60
  headers:
    Authorization: !secret givenergy_apikey
    Accept: "application/json"
    Content-Type: "application/json"
  sensor:
      - name: "GivEnergy EV UUID"
        unique_id: givenergy_ev_uuid
        value_template: '{{ value_json.data[0].uuid }}'

- resource_template: 'https://api.givenergy.cloud/v1/ev-charger/{{ states("sensor.givenergy_ev_uuid") }}/commands/enable-front-panel-led/'
  scan_interval: 5
  headers:
    Authorization: !secret givenergy_apikey
    Accept: "application/json"
    Content-Type: "application/json"
  binary_sensor:
    - name: "GivEnergy EV LED State"
      unique_id: givenergy_ev_led_state
      value_template: '{{ value_json.data.value }}'
```
in rest_command.yaml
```
givenergy_ev_leds:
  url: 'https://api.givenergy.cloud/v1/ev-charger/{{ states("sensor.givenergy_ev_uuid") }}/commands/enable-front-panel-led/'
  method: POST
  headers:
    Authorization: !secret givenergy_apikey
    Accept: "application/json"
    Content-Type: "application/json"
  payload: '{"value": {{ value }}}'
```
